defmodule Mix.Tasks.MobNew.SyncMishka do
  use Mix.Task

  @shortdoc "Vendor the Mishka Chelekom mob showcase into mob_new's templates (maintainers only)"
  @moduledoc """
  #{@shortdoc}

      mix mob_new.sync_mishka ~/code/mishka_chelekom

  The default native app `mix mob.new` generates is the Mishka Chelekom mob
  showcase: its components, the gallery that presents them, and the theme bar.
  That code is developed in the `mishka_chelekom` monorepo under
  `development/mob` (itself a `mix mob.new` project) and vendored here as EEx
  templates, because the published `mishka_chelekom` package ships neither its
  `priv/mob` component templates nor any showcase generator.

  App developers never run this. Run it after pulling the Mishka repo, then
  regenerate a project and run its tests before publishing mob_new.

  ## What it writes

    * `priv/templates/mob.new/lib/app_name/components/*.ex.eex` — the components
    * `priv/templates/mob.new/lib/app_name/showcase.ex.eex` and
      `showcase/**` — the registry, kit, gallery and per-component pages
    * `priv/templates/mob.new/lib/app_name/theme_bar.ex.eex` — the theme selector
    * `priv/templates/mob.new/test/app_name/showcase_test.exs.eex`
    * the fenced `config :mob, :extra_tags` block in `config/config.exs.eex`,
      derived from the catalog in `showcase.ex` the same way the Mishka app's
      own `mix.exs` derives its tag whitelist
    * `priv/mishka_sync.txt` — the upstream commit the templates came from

  Target directories are cleared first, so a component removed upstream is
  removed here. `home_screen.ex.eex`, `app.ex.eex` and
  `home_screen_test.exs.eex` are hand-maintained: they carry the generated
  app's own name, logo and credit footer, and the `--blank` gating.

  Module and app names are rewritten to EEx assigns (`MishkaMob` →
  `<%= module_name %>`, `mishka_mob` → `<%= app_name %>`); everything else is
  copied verbatim.
  """

  @templates "priv/templates/mob.new"
  @stamp "priv/mishka_sync.txt"
  @config Path.join(@templates, "config/config.exs.eex")

  @dirs [
    {"lib/mishka_mob/components", "lib/app_name/components"},
    {"lib/mishka_mob/showcase", "lib/app_name/showcase"}
  ]

  @files [
    {"lib/mishka_mob/showcase.ex", "lib/app_name/showcase.ex.eex"},
    {"lib/mishka_mob/theme_bar.ex", "lib/app_name/theme_bar.ex.eex"},
    {"test/mishka_mob/showcase_test.exs", "test/app_name/showcase_test.exs.eex"}
  ]

  @fence_start "# >>> mishka tags — regenerated by `mix mob_new.sync_mishka`, do not edit"
  @fence_end "# <<< mishka tags"

  # Same anchors the Mishka app's mix.exs uses: a tag is only a tag when the
  # catalog binds it to a component module (positional or keyword form), and
  # slot tags are read off @slot_tags because they have no module to anchor on.
  @register ~r/:?([a-z0-9_]+)[:,]\s*MishkaMob\.Components\.[A-Z]/
  @slots ~r/@slot_tags\s+\[([^\]]*)\]/

  @impl Mix.Task
  def run([path | _]) do
    source = resolve_source(path)
    result = sync(source, File.cwd!())

    Mix.shell().info(
      "synced #{result.files} files from #{source} (#{result.commit || "no git commit"}), " <>
        "#{length(result.tags)} tags"
    )
  end

  def run(_), do: Mix.raise("usage: mix mob_new.sync_mishka PATH_TO_MISHKA_CHELEKOM_CHECKOUT")

  @doc """
  Vendors `source` (a Mishka `development/mob` app) into the mob_new checkout at
  `repo`. Returns the file count, the tags written to the config fence, and the
  upstream commit (`nil` when `source` is not a git checkout).
  """
  @spec sync(String.t(), String.t()) :: %{
          files: non_neg_integer(),
          tags: [String.t()],
          commit: String.t() | nil
        }
  def sync(source, repo) do
    templates = Path.join(repo, @templates)

    dir_count =
      Enum.reduce(@dirs, 0, fn {src, dest}, acc ->
        dest_dir = Path.join(templates, dest)
        File.rm_rf!(dest_dir)

        files = Path.wildcard(Path.join([source, src, "**", "*.ex"]))

        Enum.each(files, fn file ->
          rel = Path.relative_to(file, Path.join(source, src))
          write_template(file, Path.join(dest_dir, rel <> ".eex"))
        end)

        acc + length(files)
      end)

    Enum.each(@files, fn {src, dest} ->
      write_template(Path.join(source, src), Path.join(templates, dest))
    end)

    catalog = File.read!(Path.join(source, "lib/mishka_mob/showcase.ex"))
    tags = tags(catalog)
    write_fence(Path.join(repo, @config), tags)

    commit = git_commit(source)
    write_stamp(Path.join(repo, @stamp), source, commit)

    %{files: dir_count + length(@files), tags: tags, commit: commit}
  end

  @doc """
  Rewrites Mishka app source into a mob_new template: pre-existing EEx markers
  are escaped first so they survive rendering, then the app's module and OTP
  names become assigns.
  """
  @spec rewrite(String.t()) :: String.t()
  def rewrite(content) do
    content
    |> String.replace("<%", "<%%")
    |> String.replace("MishkaMob", "<%= module_name %>")
    |> String.replace("mishka_mob", "<%= app_name %>")
  end

  @doc """
  The PascalCase `~MOB` tags the catalog registers — composites (`:mishka_chip`
  → `MishkaChip`) and slot tags — sorted and unique.
  """
  @spec tags(String.t()) :: [String.t()]
  def tags(catalog) do
    composites = @register |> Regex.scan(catalog, capture: :all_but_first) |> List.flatten()

    slots =
      case Regex.run(@slots, catalog, capture: :all_but_first) do
        [list] -> ~r/:([a-z0-9_]+)/ |> Regex.scan(list, capture: :all_but_first) |> List.flatten()
        nil -> []
      end

    if composites == [], do: raise(ArgumentError, "no composite tags found in the catalog")

    (composites ++ slots)
    |> Enum.map(&Macro.camelize/1)
    |> Enum.uniq()
    |> Enum.sort()
  end

  @doc "Replaces the fenced tag block in a config template with `tags`."
  @spec write_fence(String.t(), [String.t()]) :: :ok
  def write_fence(config_path, tags) do
    current = File.read!(config_path)

    block =
      [@fence_start, "config :mob, :extra_tags, ~w(" | Enum.map(tags, &("  " <> &1))] ++
        [")", @fence_end]

    updated =
      case String.split(current, @fence_start, parts: 2) do
        [before, rest] ->
          [_, tail] = String.split(rest, @fence_end, parts: 2)
          before <> Enum.join(block, "\n") <> tail

        [_only] ->
          raise ArgumentError, "#{config_path} has no `#{@fence_start}` fence to fill"
      end

    File.write!(config_path, updated)
  end

  defp write_template(src, dest) do
    File.mkdir_p!(Path.dirname(dest))
    File.write!(dest, src |> File.read!() |> rewrite())
  end

  defp write_stamp(path, source, commit) do
    File.write!(path, """
    source: #{source}
    commit: #{commit || "unknown"}
    synced: #{Date.utc_today()}
    upstream: https://github.com/mishka-group/mishka_chelekom/tree/master/development/mob
    """)
  end

  # Accepts either the monorepo root or the development/mob app itself.
  defp resolve_source(path) do
    expanded = Path.expand(path)
    nested = Path.join(expanded, "development/mob")

    cond do
      File.exists?(Path.join(nested, "lib/mishka_mob/showcase.ex")) -> nested
      File.exists?(Path.join(expanded, "lib/mishka_mob/showcase.ex")) -> expanded
      true -> Mix.raise("#{path} is not a mishka_chelekom checkout (no development/mob app)")
    end
  end

  defp git_commit(source) do
    with git when is_binary(git) <- System.find_executable("git"),
         {sha, 0} <- System.cmd(git, ["-C", source, "rev-parse", "HEAD"], stderr_to_stdout: true) do
      String.trim(sha)
    else
      _ -> nil
    end
  end
end
