defmodule Mix.Tasks.MobNew.SyncMishkaTest do
  use ExUnit.Case, async: true

  alias Mix.Tasks.MobNew.SyncMishka

  @catalog """
  defmodule MishkaMob.Showcase do
    @catalog [
      {MishkaMob.Showcase.Components.Drawer, :mishka_drawer, MishkaMob.Components.MishkaDrawer},
      {MishkaMob.Showcase.Components.Toolbar, :mishka_toolbar, MishkaMob.Components.MishkaToolbar,
       [mishka_burger: MishkaMob.Components.MishkaBurger]}
    ]

    @native_tags [:anchored]

    @slot_tags [
      :mishka_accordion_item,
      :mishka_drawer_footer
    ]
  end
  """

  describe "rewrite/1" do
    test "turns the Mishka module and app names into EEx assigns" do
      src = ~s|defmodule MishkaMob.Components.MishkaChip do\n  :code.priv_dir(:mishka_mob)\nend|

      assert SyncMishka.rewrite(src) ==
               ~s|defmodule <%= module_name %>.Components.MishkaChip do\n| <>
                 ~s|  :code.priv_dir(:<%= app_name %>)\nend|
    end

    test "leaves the Mishka component prefix alone" do
      assert SyncMishka.rewrite(":mishka_chip MishkaChip mishka_") ==
               ":mishka_chip MishkaChip mishka_"
    end

    test "escapes EEx markers already present in the source" do
      # `<%` in a vendored file would otherwise be evaluated at generation time.
      assert SyncMishka.rewrite(~s|"<%= raw %>"|) == ~s|"<%%= raw %>"|
    end
  end

  describe "tags/1" do
    test "collects composite, companion and slot tags as sorted PascalCase" do
      assert SyncMishka.tags(@catalog) == [
               "MishkaAccordionItem",
               "MishkaBurger",
               "MishkaDrawer",
               "MishkaDrawerFooter",
               "MishkaToolbar"
             ]
    end

    test "does not treat native node types as sigil tags" do
      refute "Anchored" in SyncMishka.tags(@catalog)
    end

    test "raises on a catalog without composites rather than emptying the whitelist" do
      assert_raise ArgumentError, ~r/no composite tags/, fn ->
        SyncMishka.tags("defmodule MishkaMob.Showcase do\nend")
      end
    end
  end

  describe "write_fence/2" do
    setup do
      tmp =
        Path.join(System.tmp_dir!(), "sync_mishka_fence_#{System.unique_integer([:positive])}")

      File.mkdir_p!(tmp)
      on_exit(fn -> File.rm_rf!(tmp) end)
      {:ok, tmp: tmp}
    end

    test "replaces only the fenced block", %{tmp: tmp} do
      path = Path.join(tmp, "config.exs.eex")

      File.write!(path, """
      import Config
      <%= unless blank do %>
      # >>> mishka tags — regenerated by `mix mob_new.sync_mishka`, do not edit
      config :mob, :extra_tags, ~w(
        Stale
      )
      # <<< mishka tags
      <% end %>
      """)

      SyncMishka.write_fence(path, ["MishkaChip", "MishkaPill"])
      content = File.read!(path)

      assert content =~ "import Config\n<%= unless blank do %>\n# >>> mishka tags"

      assert content =~
               "config :mob, :extra_tags, ~w(\n  MishkaChip\n  MishkaPill\n)\n# <<< mishka tags\n<% end %>"

      refute content =~ "Stale"
    end

    test "refuses a config template with no fence", %{tmp: tmp} do
      path = Path.join(tmp, "config.exs.eex")
      File.write!(path, "import Config\n")

      assert_raise ArgumentError, ~r/no `# >>> mishka tags/, fn ->
        SyncMishka.write_fence(path, ["MishkaChip"])
      end
    end
  end

  describe "sync/2" do
    setup do
      tmp = Path.join(System.tmp_dir!(), "sync_mishka_#{System.unique_integer([:positive])}")
      source = Path.join(tmp, "mishka/development/mob")
      repo = Path.join(tmp, "mob_new")
      templates = Path.join(repo, "priv/templates/mob.new")

      write = fn rel, content ->
        path = Path.join(source, rel)
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, content)
      end

      write.("lib/mishka_mob/showcase.ex", @catalog)
      write.("lib/mishka_mob/theme_bar.ex", "defmodule MishkaMob.ThemeBar do\nend\n")

      write.(
        "lib/mishka_mob/components/mishka_chip.ex",
        "defmodule MishkaMob.Components.MishkaChip do\nend\n"
      )

      write.(
        "lib/mishka_mob/components/event.ex",
        "defmodule MishkaMob.Components.Event do\nend\n"
      )

      write.("lib/mishka_mob/showcase/kit.ex", "defmodule MishkaMob.Showcase.Kit do\nend\n")

      write.(
        "lib/mishka_mob/showcase/components/chip.ex",
        "defmodule MishkaMob.Showcase.Components.Chip do\nend\n"
      )

      write.("test/mishka_mob/showcase_test.exs", "defmodule MishkaMob.ShowcaseTest do\nend\n")

      # A previously vendored component that no longer exists upstream.
      stale = Path.join(templates, "lib/app_name/components/mishka_gone.ex.eex")
      File.mkdir_p!(Path.dirname(stale))
      File.write!(stale, "gone")

      config = Path.join(templates, "config/config.exs.eex")
      File.mkdir_p!(Path.dirname(config))

      File.write!(config, """
      import Config
      # >>> mishka tags — regenerated by `mix mob_new.sync_mishka`, do not edit
      # <<< mishka tags
      """)

      on_exit(fn -> File.rm_rf!(tmp) end)
      {:ok, source: source, repo: repo, templates: templates}
    end

    test "vendors the components, showcase, theme bar and test as rewritten templates",
         %{source: source, repo: repo, templates: templates} do
      result = SyncMishka.sync(source, repo)

      assert result.files == 7
      assert result.tags == SyncMishka.tags(@catalog)

      assert File.read!(Path.join(templates, "lib/app_name/components/mishka_chip.ex.eex")) ==
               "defmodule <%= module_name %>.Components.MishkaChip do\nend\n"

      assert File.exists?(Path.join(templates, "lib/app_name/components/event.ex.eex"))
      assert File.exists?(Path.join(templates, "lib/app_name/showcase/kit.ex.eex"))
      assert File.exists?(Path.join(templates, "lib/app_name/showcase/components/chip.ex.eex"))
      assert File.exists?(Path.join(templates, "lib/app_name/theme_bar.ex.eex"))

      assert File.read!(Path.join(templates, "lib/app_name/showcase.ex.eex")) =~
               "defmodule <%= module_name %>.Showcase do"

      assert File.read!(Path.join(templates, "test/app_name/showcase_test.exs.eex")) =~
               "defmodule <%= module_name %>.ShowcaseTest do"
    end

    test "removes templates for components that vanished upstream",
         %{source: source, repo: repo, templates: templates} do
      SyncMishka.sync(source, repo)
      refute File.exists?(Path.join(templates, "lib/app_name/components/mishka_gone.ex.eex"))
    end

    test "fills the config fence and writes the sync stamp",
         %{source: source, repo: repo, templates: templates} do
      result = SyncMishka.sync(source, repo)

      config = File.read!(Path.join(templates, "config/config.exs.eex"))
      assert config =~ "config :mob, :extra_tags, ~w(\n  MishkaAccordionItem\n"
      assert config =~ "  MishkaToolbar\n)\n# <<< mishka tags"

      stamp = File.read!(Path.join(repo, "priv/mishka_sync.txt"))
      assert stamp =~ "source: #{source}"
      # The fixture is not a git checkout, so the commit is recorded as unknown.
      assert result.commit == nil
      assert stamp =~ "commit: unknown"
      assert stamp =~ "upstream: https://github.com/mishka-group/mishka_chelekom"
    end
  end
end
